[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cipher = "0.4.4"
js-sys = "0.3.82"
serde = { version = "1.0.228", features = ["derive"] }
wasm-bindgen = "0.2"
